IBM/ibm-block-csi-operator

- Makefile
- deploy/csi_driver.yaml
- pkg/controller/controller_suite_test.go
- pkg/controller/ibmblockcsi/ibmblockcsi_controller.go
- pkg/controller/ibmblockcsi_controller_test.go
- pkg/controller/node_and_volumeattachment_controller_test.go
- pkg/controller/util/utils.go
- pkg/internal/ibmblockcsi/static_resource_generator.go
create the CSIDriver object when an IBMBlockCSI is created.
> Create automatically the ibm CSIDriver CR when installing the driver.

- deploy/installer/generated/ibm-block-csi-operator.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.0.0/ibm-block-csi-operator.v1.0.0.clusterserviceversion.yaml
- deploy/role.yaml
1. add csidriver get list watch permissions.
2. remove unused permissions
> fix csidriver roles

- pkg/controller/ibmblockcsi/syncer/csi_controller.go
- pkg/controller/ibmblockcsi/syncer/csi_node.go
according to the result in https://jira.xiv.ibm.com/browse/CSI-643
> set more meaningful resources requests and limits

- pkg/controller/ibmblockcsi/syncer/csi_controller.go
- pkg/controller/ibmblockcsi/syncer/csi_node.go
Signed-off-by: 27149chen <alex1988@outlook.com>
> remove liveness probe from sidecars

- README.md
- deploy/olm-catalog/ibm-block-csi-operator/1.0.0/ibm-block-csi-operator.v1.0.0.clusterserviceversion.yaml
Do the following on both readme file and the OLM readme file(used in openshift GUI).
1. secret and storage class config 
2. Fix support matrix
3. Add worker prepare
4. Add link to KC
5. iscsi loging at least two IPs - make it clearer in the readme file.
CSI-568
> Update readme and olm readme

- pkg/controller/ibmblockcsi/syncer/csi_node.go
> CSI-1191_iscsi_login_deployment

- deploy/crds/csi.ibm.com_v1_ibmblockcsi_cr.yaml
https://kubernetes-csi.github.io/docs/sidecar-containers.html#versioning
> align community sidecars versions to k8s 1.16

- build/ci/Dockerfile.unittest
- hack/update-crds.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ibm/ibm-block-csi-operator/60)
> adapt UT to be cross architecture

- deploy/olm-catalog/ibm-block-csi-operator/1.1.0/ibm-block-csi-operator.v1.1.0.clusterserviceversion.yaml
change capability from "Seamless Upgrades" to "Basic Install"
> change from "Seamless Upgrades" to "Basic Install"

- pkg/controller/ibmblockcsi/syncer/csi_controller.go
increase provisioner and attacher sidecar timeout interval to 30s
> increase sidecar timeout interval to 30s

- README.md
Align operator and driver readme files and yaml examples
Parallel driver review: https://github.com/IBM/ibm-block-csi-driver/pull/167
> CSI-1305_readme_allignment

- pkg/controller/ibmblockcsi/syncer/csi_controller.go
Increase liveness probe FailureThreshold and timeout
> liveness_probed_timeout - increase timeout and failuresThreshold

- deploy/olm-catalog/ibm-block-csi-operator-community/1.2.0/ibm-block-csi-operator.v1.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/ibm-block-csi-operator.v1.2.0.clusterserviceversion.yaml
according to https://github.com/IBM/ibm-block-csi-operator/pull/74 and previous changes
> CSI-1618 align csv descriptions by current readme content

- deploy/olm-catalog/ibm-block-csi-operator-community/1.2.0/ibm-block-csi-operator.v1.2.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/ibm-block-csi-operator.v1.2.0.clusterserviceversion.yaml
a continuation of https://github.com/IBM/ibm-block-csi-operator/pull/77
> Task/csi 1542 advance "replaces" field

- deploy/crds/csi.ibm.com_v1_ibmblockcsi_cr.yaml
- deploy/crds/csi.ibm.com_v1_ibmblockcsi_cr_ocp.yaml
https://kubernetes-csi.github.io/docs/sidecar-containers.html#versioning
> CSI-1751 update sidecars versions

- README.md
- deploy/olm-catalog/ibm-block-csi-operator-community/1.3.0/ibm-block-csi-operator.v1.3.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/ibm-block-csi-operator.v1.3.0.clusterserviceversion.yaml
> CSI-1848 update READMEs

- build/Dockerfile.operator
similar to https://github.com/IBM/ibm-block-csi-operator/pull/110
> CSI-2768 bump base image version

- deploy/installer/generated/ibm-block-csi-operator.yaml
- deploy/olm-catalog/ibm-block-csi-operator-community/1.5.0/ibm-block-csi-operator.v1.5.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.5.0/manifests/ibm-block-csi-operator.v1.5.0.clusterserviceversion.yaml
- deploy/role.yaml
- pkg/controller/ibmblockcsi/ibmblockcsi_controller.go
based on: https://docs.openshift.com/container-platform/4.6/nodes/pods/nodes-pods-secrets.html#nodes-pods-secrets-updating_nodes-pods-secrets
and: https://stackoverflow.com/a/59051313
> CSI-2777 fix driver stuck on creating after token change

- pkg/internal/ibmblockcsi/default_setter.go
always set default nil slices to allow finalizer initialization afterwards
> CSI-2716 fix deployment

- NOTICES
> Feature/csi 2726 electronic license 1.5.0

- build/Dockerfile.operator
- deploy/crds/csi.ibm.com_ibmblockcsis_crd.yaml
- deploy/crds/csi.ibm.com_v1_ibmblockcsi_cr.yaml
- deploy/installer/generated/ibm-block-csi-operator.yaml
- deploy/operator.yaml
- deploy/service_account.yaml
- version/version.go
It's based on [this](https://github.com/IBM/ibm-block-csi-operator/pull/120/files?file-filters%5B%5D=) commit.
> CSI-2842 bump operator version to 1.6.0

- pkg/controller/ibmblockcsi/ibmblockcsi_controller.go
workaround for https://github.com/kubernetes/kubernetes/issues/67250
> CSI-2854 sync controller image when not running

- deploy/crds/csi.ibm.com_ibmblockcsis_crd.yaml
- deploy/installer/generated/ibm-block-csi-operator.yaml
- deploy/olm-catalog/ibm-block-csi-operator-community/1.6.0/csi.ibm.com_ibmblockcsis_crd.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.6.0/manifests/ibmblockcsis.csi.ibm.com.crd.yaml
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/
> CSI-2413 bump the CRD api version

- pkg/controller/ibmblockcsi/syncer/csi_controller.go
adding a flag for topology support in controller
> CSI-2899 topology controller support

- build/Dockerfile.operator
similar to https://github.com/IBM/ibm-block-csi-operator/pull/125
> CSI-2957 bump base image version

- deploy/olm-catalog/ibm-block-csi-operator-community/1.6.0/csi.ibm.com_ibmblockcsis_crd.yaml
- deploy/olm-catalog/ibm-block-csi-operator-community/1.6.0/ibm-block-csi-operator.v1.6.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.6.0/manifests/ibm-block-csi-operator.v1.6.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.6.0/manifests/ibmblockcsis.csi.ibm.com.crd.yaml
Reverts IBM/ibm-block-csi-operator#163
> Revert "Bug/csi 3055 icp crd license accept errors"

- build/Dockerfile.operator
> CSI-3029 bump base image version

- deploy/crds/csi.ibm.com_v1_ibmblockcsi_cr.yaml
- deploy/olm-catalog/ibm-block-csi-operator-community/1.7.0/manifests/ibm-block-csi-operator.v1.7.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.7.0/manifests/ibm-block-csi-operator.v1.7.0.clusterserviceversion.yaml
https://kubernetes-csi.github.io/docs/sidecar-containers.html#versioning
> CSI-3093 update sidecars versions

- deploy/olm-catalog/ibm-block-csi-operator-community/ci.yaml
https://operator-framework.github.io/community-operators/operator-ci-yaml/#reviewers
> CSI-3407 add OperatorHub reviewers

- build/Dockerfile.operator
similar to https://github.com/IBM/ibm-block-csi-operator/pull/200
> CSI-3663 bump base image

- build/ci/run_olm_validation.sh
fix https://github.com/IBM/ibm-block-csi-operator/pull/185
> avoid docker in docker

- controllers/syncer/csi_controller.go
- controllers/syncer/csi_node.go
continuation of https://github.com/IBM/ibm-block-csi-operator/pull/201
> CSI-2887 align containers name

- build/Dockerfile.operator
https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?tag=all
> CSI-3736 bump base image

- build/Dockerfile.operator
- build/ci/Jenkinsfile
- config/crd/bases/csi.ibm.com_ibmblockcsis.yaml
- config/crd/patches/labels_patch.yaml
- config/manager/manager.yaml
- config/rbac/service_account.yaml
- config/samples/csi.ibm.com_v1_ibmblockcsi_cr.yaml
- deploy/installer/generated/ibm-block-csi-operator.yaml
- version/version.go
> change product version to 1.10.0

- build/Dockerfile.operator
similar to https://github.com/IBM/ibm-block-csi-operator/pull/246
> CSI-4256 bump base image

- README.md
> CSI-4492 align readme and csv

- build/Dockerfile.operator
> CSI-4473 update base image

- NOTICES
> CSI-4481 merge elicense

- deploy/olm-catalog/ibm-block-csi-operator-community/1.10.0/manifests/ibm-block-csi-operator.v1.10.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.10.0/manifests/ibm-block-csi-operator.clusterserviceversion.yaml
> fix example annotation

- build/ci/multiarch/helper_to_push_csi_images_and_manifests.sh
the changes that we used for the publication
> add host definer

- deploy/olm-catalog/ibm-block-csi-operator-community/1.10.0/manifests/ibm-block-csi-operator.v1.10.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.10.0/manifests/ibm-block-csi-operator.clusterserviceversion.yaml
> change definition to definer

- api/v1/hostdefinition_types.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/csi.ibm.com_hostdefinitions.yaml
- deploy/installer/generated/ibm-block-csi-operator.yaml
- deploy/olm-catalog/ibm-block-csi-operator-community/1.11.0/manifests/csi.ibm.com_hostdefinitions.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.11.0/manifests/csi.ibm.com_hostdefinitions.yaml
> CSI-4747/ support hostDefinition ioGroup in operator

- config/rbac/role.yaml
- config/samples/csi.ibm.com_v1_ibmblockcsi_cr.yaml
- controllers/ibmblockcsi_controller.go
- controllers/internal/crutils/static_resource_generator.go
- controllers/syncer/csi_controller.go
- deploy/installer/generated/ibm-block-csi-operator.yaml
- deploy/olm-catalog/ibm-block-csi-operator-community/1.11.0/manifests/ibm-block-csi-operator.v1.11.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.11.0/manifests/ibm-block-csi-operator.clusterserviceversion.yaml
- pkg/config/constants.go
- pkg/config/resources.go
Signed-off-by: Elena Gershkovich <elenage@il.ibm.com>
> Add volumegroup sidecar to CSI driver operator

- deploy/olm-catalog/ibm-block-csi-operator-community/1.11.0/manifests/ibm-block-csi-operator.v1.11.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.11.0/manifests/ibm-block-csi-operator.clusterserviceversion.yaml
Signed-off-by: Elena Gershkovich <elenage@il.ibm.com>
> Fix yamls for operator

- config/samples/csi.ibm.com_v1_ibmblockcsi_cr.yaml
- controllers/syncer/csi_controller.go
- deploy/olm-catalog/ibm-block-csi-operator-community/1.11.0/manifests/ibm-block-csi-operator.v1.11.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-block-csi-operator/1.11.0/manifests/ibm-block-csi-operator.clusterserviceversion.yaml
Signed-off-by: Elena Gershkovich <elenage@il.ibm.com>
> Add parameters to volume group operator

- controllers/internal/crutils/static_resource_generator.go
Signed-off-by: Elena Gershkovich <elenage@il.ibm.com>
> Add role for VG contents status

- controllers/syncer/csi_controller.go
> add multiple-vgs-to-pvc flag

- controllers/internal/crutils/static_resource_generator.go
> add storageClass to volumeGroup

- build/Dockerfile.operator
> update base images

- NOTICES
> add elicense

- config/samples/csi.ibm.com_v1_ibmblockcsi_cr.yaml
change csi-provisioner version in CR to match version in csv
> CSI-5299_change provisioner version
